### ISSUE TITLE
Valo vaadin-button: text isn't centered vertically

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-themes#21]
Could be reproduced here https://github.com/vaadin/bakery-app-starter-polymer/pull/24

Actual | Expected
---------|-------------
![](https://i.imgur.com/RDG01Rn.png) | ![](https://i.imgur.com/ob4DbKD.png)

**Comment by jouni** [comment]
Browser and platform?

**Comment by limonte** [comment]
Chrome/Linux

**Comment by jouni** [comment]
I also see this also in the Bakery app, on macOS, all browsers. But I’m not seeing it in the vaadin-themes demo. Need to investigate.

**Comment by jouni** [comment]
Ah, found the culprit. Currently, when using an icon in a button, you need to add `theme="icon"` to it, to make the alignment work nicely. So at the moment, this should be fixed in the Bakery app. 

@samiheikki, can you handle that (add `theme="icon"` to all buttons that have an `<iron-icon>` inside them?

**Comment by samiheikki** [comment]
Sure

**Comment by jouni** [comment]
This issue was moved to vaadin/vaadin-valo-theme#3
