### ISSUE TITLE
Split themes into separate repos?

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-themes#48]
Should we split the current Valo and Material themes into their own repos instead of having both in this one?

It would give us more flexibility in just focusing on Valo at the moment, and stamping a 1.0 stable sooner.

Also, it could make it simpler in the future to start implementing a new theme, as we could make pre-releases of that independently of these two themes.

Another option, I guess, could be that we still focus on Valo 1.0 right now, and move the current Material theme to a “2.0-preview” branch and merge the Valo updates there.

I appreciate all thoughts on this, not just the team’s opinion!

**Comment by tomivirkki** [comment]
I’m voting for separate theme repos. Unless you’re a Vaadin Elements demo developer, you’ll only need one theme in your app. I’d rather do the deciding in dependencies instead of import path.

Also, because of what you said about the flexibility in focusing in Valo. It just makes versioning more meaningful to have separate products versioned separately.

**Comment by jouni** [comment]
Thanks for the comments. We agreed to split the repo, and I’m currently working on it. This repo is deprecated from this point on. I’ll be moving any theme specific issues to their respective new repos at some point.
